
package ViewLayer;

import BusinessModelLayer.Contactos;
import BusinessModelLayer.Estados;
import BusinessModelLayer.Municipio;
import javax.swing.JOptionPane;

/**
 *
 * @author AJLJ-
 */
public class nContactos extends javax.swing.JDialog {

    private int idContacto = 0;
    private Contactos contacto = new Contactos();
    private Estados estado = new Estados();
    
    public nContactos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        NombreS();
        NombreM();
    }
    
    public nContactos(){
         initComponents();
         NombreS();
         NombreM();
    }
    
    public nContactos(int idContacto){
        initComponents();
        this.idContacto = idContacto;
        
        contacto.setIdContacto(idContacto);
        contacto.GetById();
        //tIDC.setText(""+contacto.getIdContacto());
        tCP.setText(""+contacto.getCodigoPostal());
        //tNombre.setText(contacto.getNombre());
        //tEntidad.setText(contacto.getEntidad());
        //tComuna.setText(contacto.getComuna());
        tCalle.setText(contacto.getCalle());
        tTelefono.setText(""+contacto.getTelefono());
        NombreS();
        NombreM();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tCalle = new javax.swing.JTextField();
        tTelefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bAgregar = new javax.swing.JButton();
        tCP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cEstados = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();
        cMunicipio = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("Municipio:");

        bCancelar.setText("Cancelar");

        jLabel5.setText("Codigo postal:");

        jLabel6.setText("Telefono:");

        jLabel7.setText("Calle:");

        bAgregar.setText("Guardar");
        bAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarActionPerformed(evt);
            }
        });

        jLabel2.setText("Estado:");

        jLabel3.setText("Nombre:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tCP, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(tTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tCalle, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(cEstados, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cMunicipio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(bCancelar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(tCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAgregar)
                    .addComponent(bCancelar))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void NombreS(){
        for(int i = 0; i< new Estados().GetAllModel().getRowCount(); i++){
            cEstados.addItem("" + new Estados().GetAllModel().getValueAt(i, 1));
        }
        
    }
    
    public void NombreM(){
        for(int i = 0; i< new Municipio().GetAllModel().getRowCount(); i++){
            cMunicipio.addItem("" + new Municipio().GetAllModel().getValueAt(i, 2));
        }
    }
    
    private void bAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarActionPerformed
         
        int idEstado = 0;
      
         for(int i = 0; i< new Estados().GetAllModel().getRowCount(); i++){
                if(new Estados().GetAllModel().getValueAt(i, 1).equals(cEstados.getItemAt(cEstados.getSelectedIndex()))){
                        idEstado = Integer.parseInt("" + new Estados().GetAllModel().getValueAt(i, 0));
                      
                    }
             }
        
        int idMunicipio = 0;
       
      
         for(int i = 0; i< new Municipio().GetAllModel().getRowCount(); i++){
                if(new Municipio().GetAllModel().getValueAt(i, 2).equals(cMunicipio.getItemAt(cEstados.getSelectedIndex()))){
                        idMunicipio = Integer.parseInt("" + new Municipio().GetAllModel().getValueAt(i, 0));
                        
                    }
             }
    

        if(contacto.getIdContacto()> 0){

            //contacto.setIdContacto(Integer.parseInt(tIDC.getText()));
            contacto.setCodigoPostal(Integer.parseInt(tCP.getText()));
            contacto.setEntidad(idEstado);
            contacto.setComuna(idMunicipio);
            contacto.setCalle(tCalle.getText());
            contacto.setTelefono(Integer.parseInt(tTelefono.getText()));
            

            //farmacia.setActivo(1);
            if(contacto.Update()){
                JOptionPane.showMessageDialog(null,"Contacto actualizado correctamente");
                this.dispose();
            }

        }else{
            if(new Contactos(0,
                tNombre.getText(),
                Integer.parseInt(tCP.getText()),
                idEstado,
                idMunicipio,
                tCalle.getText(),
                Integer.parseInt(tTelefono.getText())).add()){
            JOptionPane.showMessageDialog(null,"Contacto agregado correctamente");
            this.dispose();
            }

    }//GEN-LAST:event_bAgregarActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                nContactos dialog = new nContactos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JComboBox<String> cEstados;
    private javax.swing.JComboBox<String> cMunicipio;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tCP;
    private javax.swing.JTextField tCalle;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTextField tTelefono;
    // End of variables declaration//GEN-END:variables
}
