/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewLayer;

import BusinessModelLayer.Localidades;
import BusinessModelLayer.Municipio;
import javax.swing.JOptionPane;

/**
 *
 * @author AJLJ-
 */
public class nLocalidades extends javax.swing.JDialog {

   private int idLocalidad = 0;
    private Localidades localidad = new Localidades();
    
    
    
    
    public nLocalidades(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        NombreM();
    }
    
    public nLocalidades(){
         initComponents();
        NombreM();
    }
    
    public nLocalidades(int idLocalidad){
        initComponents();
        this.idLocalidad = idLocalidad;
        localidad.setIdLocalidad(idLocalidad);
        localidad.GetById();
        tNombre.setText(localidad.getLocalidad());
        //tMunicipio.setText(""+localidad.getIdMunicipio());
        NombreM();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bAgregar = new javax.swing.JButton();
        tNombre = new javax.swing.JTextField();
        bCancelar = new javax.swing.JButton();
        cMunicipios = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel6.setText("Nombre:");

        jLabel7.setText("Municipio");

        bAgregar.setText("Guardar");
        bAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarActionPerformed(evt);
            }
        });

        bCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cMunicipios, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(bAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(bCancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cMunicipios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAgregar)
                    .addComponent(bCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void NombreM(){
        
        for(int i = 0; i< new Municipio().GetAllModel().getRowCount(); i++){
            cMunicipios.addItem("" + new Municipio().GetAllModel().getValueAt(i, 2));
        }
    }
    
    
    
    private void bAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarActionPerformed
       
        int idMunicipio = 0;
       for(int i = 0; i< new Municipio().GetAllModel().getRowCount(); i++){
            if(new Municipio().GetAllModel().getValueAt(i, 2).equals(cMunicipios.getItemAt(cMunicipios.getSelectedIndex()))){
               idMunicipio = Integer.parseInt("" + new Municipio().GetAllModel().getValueAt(i, 0));
            }
       }

        if(localidad.getIdLocalidad()> 0){

            //usuario.setIdUsuario(0);
            //localidad.setIdMunicipio(idSucursal);
           // localidad.setIdContacto(Integer.parseInt(tIDC.getText()));
            localidad.setLocalidad(tNombre.getText());
            localidad.setIdMunicipio(idMunicipio);
            
           // localidad.setTipoUsuario(tTipo.getText());
            //usuario.setUsuario(tNombre.getText());
            //usuario.setPassword(tMunicipio.getText());

            //farmacia.setActivo(1);
            if(localidad.Update()){
                JOptionPane.showMessageDialog(null,"Usuario actualizado correctamente");
                this.dispose();
            }

        }else{
            //usuario.Empezar();
            if(new Localidades(0,
                idMunicipio,
                tNombre.getText()
                ).add()){
            JOptionPane.showMessageDialog(null,"Usuario agregado correctamente");
            this.dispose();
        }

        }
    }//GEN-LAST:event_bAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nLocalidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nLocalidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nLocalidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nLocalidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                nLocalidades dialog = new nLocalidades(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JComboBox<String> cMunicipios;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tNombre;
    // End of variables declaration//GEN-END:variables
}
